### PR TITLE
Update Gradle wrapper to Gradle 4.3

### PR DESCRIPTION
**Pull request by eriwen**

### CODE REVIEW

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Release notes https://github.com/gradle/gradle/releases/tag/v4.3.0

**Comment by artem-zinnatullin** [comment]
Thanks!

**Comment by artem-zinnatullin** [comment]
@eriwen hm, just updated project at work from Gradle 4.2.1 to 4.3 and there was a `gradle-wrapper.jar` change

**Comment by eriwen** [comment]
@artem-zinnatullin That is expected. I apologize for not running the wrapper and committing the JAR as well.

**Pull request merged**
