### PR TITLE
Execution model improvements

### PR DESCRIPTION
**Pull request by jskierbi**
Multiple changes mainly discussed in #39

1. Fixed execution order of ```beforeOn``` and ```afterOn```
2. Added ```beforeEach``` and ```afterEach``` idiom on ```Spek``` level
3. Fixed and improved runners, both Console runner and JUnitClassRunner
4. Improved spek-tests module: now each test is run against both Console runner an JUnitClassRunner, so we can expect that both **runners behaves in exactly same way**
5. Added some new tests in spek-tests module (exception reporting, before/after each)

Remarks:
IntelliJ integration works ok (i.e. JUnit execution tree updates as it should), however because of how integration works, I had to write test execution in unexpected place. Please note ```JUnitClassRunner#getDescription``` and ```JUnitClassRunner#run(RunNotifier)``` - actual tests are executed in first method storing results inside runner, reporting the results in latter method.

### CODE REVIEW

**Comment by hhariri** [comment]
Thanks @jskierbi. Assigning to @akozlova

**Comment by jskierbi** [comment]
@hhariri @akozlova please tell me have you found time to look at this pr?

**Comment by akozlova** [comment]
sorry, didn't have time. will check this week.

**Comment by TwistedEquations** [comment]
Any progress on this? It is an ideal solution to an issue im having.

**Comment by hhariri** [comment]
@jskierbi you seen https://github.com/JetBrains/spek/pull/69 ?

**Comment by jskierbi** [comment]
@hhariri yes already commented

Is resolving conflicts for this PR sensible? I use the code already in production for an Android project, but I really don't know whether this is expected dev direction for spek (especially with this hacked JUnit runner, that may not work somewhere...)

**Comment by akozlova** [comment]
Sorry that it took so long for me to process. I was trying to check all this staff against junit5 (lambda), As far as I can see, you'll need to provide separate TestEngine and then you'll be able to provide navigation to the file:line; rerun would be possible because test ids would be unique and serializable so IDEA would be able to leave only selected nodes, etc. So for the time being: what is done is a hack but it should work before junit 5 release. For junit 5, it would be better to provide separate support (need to reconsider in couple of months). Thanks

**Comment by hhariri** [comment]
@jskierbi Is there an email to reach you on? Mine is hadi at jetbrains....

**Comment by hhariri** [comment]
Most of these changes have been incorporated or are now incompatible with the new 1.0 mode. Thanks for all the work, ideas and suggestions.

**Pull request closed without merging**
