### PR TITLE
Update compiler to use Beta-4584

### PR DESCRIPTION
**Pull request by ByunghanYoo**

### CODE REVIEW

**Comment by ByunghanYoo** [comment]
@hhariri Check this pull request please.

**Comment by hhariri** [comment]
Thanks. It seems good to go except you've checked in a couple of .idea files for inspections. Is this intentional?

**Comment by ByunghanYoo** [comment]
In the .gitignore file, only three ".idea/dictionaries/*", ".idea/workspace.xml", ".idea/artifacts" were there. So, can I delete all the files in the .idea directory? And then can I add the ".idea/*" in the .gitignore file?

**Comment by hhariri** [comment]
Yes. No objections from me. Once people import the project they can get the files generated. Thanks.

**Comment by ByunghanYoo** [comment]
@hhariri OK. I updated .gitignore and removed *iml files and .idea directory.

**Comment by hhariri** [comment]
Thanks!

**Pull request merged**
