### PR TITLE
Prevent nested tests and actions

### LINKED ISSUE #331: Prevent users from nesting actions.
```kotlin
Spec : Spek({
  on("some action") {
  
    action.run()

    it("does something") {}

    on("nested action") {
      // We should either support that or fail the spec, ideally at compile time.
    }
  }
})
```

Possible solutions:

- Detect problem at runtime and throw exception
- `@DslMarker` https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-dsl-marker/

### PR DESCRIPTION
**Pull request by tokou**
Fixes #331 and #371

### CODE REVIEW

**Comment by artem-zinnatullin** [comment]
Tests?

**Comment by tokou** [comment]
I have a test that fails the compilation of the project.
But don't know how to write it an assertion about that, that's why I didn't submit it :)

**Comment by tokou** [comment]
```
@Test
    fun testNestedSpek() {
        class TestSpek: Spek({
            group("group") {
                test("test") {
                    test("another test") {}
                }
                action("action") {
                    action("another action") {}
                }
            }
        })
    }
```

For reference

**Comment by artem-zinnatullin** [comment]
Well, yeah `DeprecationLevel.ERROR` prevents compilation

Ok, leave it for us then, we can add integration test later :)

**Review by artem-zinnatullin — APPROVED** [review]
LGTM :)

**Comment by raniejade** [comment]
This is now obsolete since we now use `@DslMarker` to prevent nesting. Sorry for not merging this asap.

**Pull request closed without merging**
