### PR TITLE
Run destructor callback when memoized value leaves scope

### PR DESCRIPTION
**Pull request by tadfisher**
Add a `destructor` callback to handle cleanup of mutable or external state when
a `memoized()` value leaves scope. This would be useful for shared test fixtures
which require some teardown action, and extensions could allow direct adaptation
of JUnit-style "before" and "after" actions.

### CODE REVIEW

**Review by raniejade — APPROVED** [review]
LGTM, @artem-zinnatullin can you please check?.

**Comment by arturdryomov** [comment]
Awesome! Double respect points for a test coverage ;-) 

Isn’t it possible to achieve a similar cleanup behavior doing `beforeEachTest` or `afterEachTest` though?

**Comment by raniejade** [comment]
@ming13 It is possible but this will prevent you from mixing incompatible `CachingMode` and fixtures (e.g. `CachingMode.Group` with a `(before/after)EachTest`).

**Comment by raniejade** [comment]
Merged, thanks @tadfisher!

**Pull request merged**
