### PR TITLE
Remove JetBrains project references

### PR DESCRIPTION
**Pull request by arturdryomov**

### CODE REVIEW

**Comment by hhariri** [comment]
Not sure if some of these might effect Bintray publishing...

**Comment by arturdryomov** [comment]
@hhariri Yep, that’s worth checking.

**Comment by raniejade** [comment]
I reserved https://bintray.com/spekframework a while back, let me know your usernames so I can add you.

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by raniejade** [comment]
Just need to update the `bintray_user` and `bintray_api_key` passed in the TC build.

**Comment by arturdryomov** [comment]
@raniejade, so this one is good to merge?

**Comment by raniejade** [comment]
Yes, merge away!

**Comment by arturdryomov** [comment]
@raniejade, actually I cannot, so do it when ready, please.

**Pull request merged**
