### PR TITLE
Update to Gradle 4.4.1

### PR DESCRIPTION
**Pull request by raniejade**

### CODE REVIEW

**Comment by raniejade** [comment]
@artem-zinnatullin

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Interesting, looks like Dokka's poms are breaking plugin resolution since Gradle 4.4 https://github.com/Kotlin/dokka/issues/146#issuecomment-350735405

**Comment by raniejade** [comment]
A workaround is also mentioned in the issue, I'll see if it works.

**Comment by artem-zinnatullin** [comment]
Looks like there is no good solution until Dokka will fix it on their side and release new version

**Comment by artem-zinnatullin** [comment]
There is also a comment stating that workaround doesn't work though

**Comment by raniejade** [comment]
Oh well, we will just have to wait.

**Comment by lptr** [comment]
I submitted #356 that works around the Dokka issue and also upgrades to Gradle 4.4.1.

**Comment by artem-zinnatullin** [comment]
Closing in favor of #356

**Pull request closed without merging**
