### PR TITLE
Publish 2.x snapshots

### PR DESCRIPTION
**Pull request by raniejade**
Use artifactory to publish to `oss.jfrog.org`, also removed `git-versioning` and manually set version to `2.0.0-SNAPSHOT`.

### CODE REVIEW

**Comment by raniejade** [comment]
@artem-zinnatullin

**Comment by raniejade** [comment]
@artem-zinnatullin wanna take a look and take over?

**Review by artem-zinnatullin — APPROVED** [review]

**Comment by artem-zinnatullin** [comment]
Looks good to me, but we don't invoke publishing tasks on CI, I can do this in a separate PR if it sounds good to you

**Comment by raniejade** [comment]
Sure, go ahead. I can provide `bintrayUser` and `bintrayApiKey` properties, these are my personal keys as bintray does not have organizational api keys.

**Comment by artem-zinnatullin** [comment]
@raniejade sounds good, but let's do it through Travis encrypted env variables? I'll prepare a PR and you'll just need to follow instructions on how to set them on Travis

**Pull request merged**
