### PR TITLE
Introduce fixture aliases for Gherkin style

### LINKED ISSUE #799: Introduce fixture aliases in gherkin style
The following fixture aliases will be introduced:
- `Scenario.beforeScenario` -> `Scenario.beforeGroup`
- `Scenario.afterScenario` -> `Scenario.afterGroup`
- `Scenario.beforeEachStep` -> `Scenario.beforeEachTest`
- `Scenario.afterEachStep` -> `Scenario.afterEachTest`
- `Feature.beforeEachScenario` -> `Feature.beforeEachGroup`
- `Feature.afterEachScenario` -> `Feature.afterEachGroup`
- `Feature.beforeFeature` -> `Feature.beforeGroup`
- `Feature.afterFeature` -> `Feature.afterGroup`

The aliased fixtures will be deprecated in the context of the `gherkin` style. This can be done by:

```kotlin
class Feature(val delegate: GroupBody): LifecycleAware by delegate {
   ...

   @Deprecated(..., replaceWith = ReplaceWith("beforeEachScenario"))
   override fun beforeEachGroup(fixture: Fixture) { delegate.beforeGroup(fixture) }
}
```

### PR DESCRIPTION
**Pull request by jcornaz**
Hi, 

This PR Resolves #799 

Done during [Basel HackerGarten](https://hackergarten.net/) with: @marvinbuff and @AdrianAgr

Hope you'll like it and find it helpful.

### CODE REVIEW

**Review by raniejade — CHANGES_REQUESTED** [review]
Looking good! Thanks for the PR. Can you rewrite the test to not use `kotlin-test`? See https://github.com/spekframework/spek/tree/2.x/integration-test/src/jvmTest/kotlin/org/spekframework/spek2 for examples. Put them in the same package as well :)

**Comment by jcornaz** [comment]
@raniejade

I moved the tests to `integration-test` as requested.

However, do you know that they are not evaluated?

You can easily get convinced that there is a problem by going at the following line: https://github.com/spekframework/spek/blob/b91b336e1081ac0e0bd63eeeb8494706fc82bd2d/integration-test/src/jvmTest/kotlin/org/spekframework/spek2/ScopeValueAccessTest.kt#L13

(on the main branch: `2.x`)

Change the expected value (of `1` by `42`) and run the tests (`./gradlew jvmTest`). The build is successful!

**Comment by raniejade** [comment]
@jcornaz thanks for the report! I'll take a look at it, pretty sure it was working before.

**Review by raniejade — APPROVED** [review]
Aside from the test not working, everything else is looking good. I'll merge this and just investigate the test issue. Thanks for the contribution!

**Comment by raniejade** [comment]
@jcornaz found the issue (not really an issue)

> Change the expected value (of 1 by 42) and run the tests (./gradlew jvmTest). The build is successful!

To run the spek tests please use `jvmSpekTest` the reason it's different is because the `integration-test` module is using the Spek's experimental gradle plugin.

**Pull request merged**
