### PR TITLE
Add release-step for IntelliJ-plugin for 2019.3;

### LINKED ISSUE #829: Support IntelliJ IDEA 2019.3
Issue #821 should add support for IntelliJ IDEA 2019.3, but as it is now publicly available, the plugin no longer works. When reviewing the change for that issue (https://github.com/spekframework/spek/pull/821/commits/48d34b26d2d7e242dfe5dc85da83c0295688cc00) it dawned upon me that only the Azure pipeline for testing that version was added, not for releasing it...

### PR DESCRIPTION
**Pull request by bdalenoord**
Fixes #829

### CODE REVIEW

**Review by raniejade — APPROVED** [review]

**Comment by raniejade** [comment]
Thanks for the PR! :)

**Comment by spriteye** [comment]
@raniejade Would you like to merge this PR? I really want to use Spek in the new IntelliJ. 😄

**Comment by raniejade** [comment]
@spriteye oops, yeah. Sorry about that!

**Comment by jcornaz** [comment]
Thanks @raniejade for the merge!

Do you need to release the IJ plugin so that we can get access to it?

https://plugins.jetbrains.com/plugin/10915-spek-framework/versions

**Comment by raniejade** [comment]
It is waiting approval from Jetbrains - so we have to wait. Also, the plugin will be available under the dev channel for now (see here: https://plugins.jetbrains.com/plugin/10915-spek-framework/versions). I'm still not done with `2.0.9` (https://github.com/spekframework/spek/milestone/16), but if the demand is high will probably push back the unfinished tickets to the next release and trigger a full release on the weekend.

**Pull request merged**
