### PR TITLE
added more test cases and functions in android sample

### PR DESCRIPTION
**Pull request by harshitsaamu**
Added more calculator functions and their corresponding test-cases in android sample

### CODE REVIEW

**Review by vanniktech — COMMENTED** [review]
What's the motivation?

**Comment by harshitsaamu** [comment]
To work with multiple test cases

**Review by raniejade — CHANGES_REQUESTED** [review]
@harshitsaamu if you could rework this tests and make it more realistic I'll be happy to merge it. The example is not a good to begin with, `should return 4` doesn't really tell what you are trying to test.

**Comment by raniejade** [comment]
Closing for lack of activity.

**Pull request closed without merging**
